
name: day1- Building blocks

on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps: 
      - name: hello
        run: echo 'Hello world'
  echo-bye: 
    runs-on: ubuntu-latest
    steps:
      - name: Failed
        run: |
          echo "failed"
          exit 1   
      - name: bye
        run: echo "Bye"       